"use client";
import { useEffect, useMemo, useState } from "react";
import { ArrowDown, ArrowLeft, ArrowRight, ArrowUp, Check, ChevronDown, Download, Eye, FilePlus2, FileText, LayoutTemplate, Link2, Menu, Plus, RotateCcw, Sparkles, Trash2, UserRound, WandSparkles } from "lucide-react";
import styles from "./page.module.css";

type Resume = { name:string; role:string; email:string; phone:string; location:string; website:string; summary:string; experience:{role:string; company:string; dates:string; description:string}[]; education:{degree:string; school:string; dates:string}[]; skills:string; accent:string; template:string };
const starter:Resume={name:"Alex Morgan",role:"Product Designer",email:"alex.morgan@email.com",phone:"+1 (415) 555-0138",location:"San Francisco, CA",website:"alexmorgan.design",summary:"Curious product designer crafting thoughtful digital experiences that make complex things feel simple. I bring a balance of systems thinking, visual craft, and a deep respect for the people on the other side of the screen.",experience:[{role:"Senior Product Designer",company:"Northstar Studio",dates:"2022 — Present",description:"Lead end-to-end design for a suite of AI-powered productivity tools used by 40,000+ teams.\nBuilt a scalable design system that cut design-to-development handoff time by 35%.\nPartner with product and engineering to turn ambiguous problems into clear, testable ideas."},{role:"Product Designer",company:"Forma Labs",dates:"2019 — 2022",description:"Redesigned the core onboarding journey, improving activation by 28%.\nRan customer interviews and usability studies to guide a new mobile-first roadmap."}],education:[{degree:"B.A. Interaction Design",school:"California College of the Arts",dates:"2015 — 2019"}],skills:"Product strategy · Interaction design · Prototyping · Design systems · Figma · Research · Accessibility · Workshop facilitation",accent:"#8f6cff",template:"Editorial"};
const colors=["#8f6cff","#276c5c","#cf7059","#3975ba","#bd8b36"];
export default function Home(){
 const [resume,setResume]=useState<Resume>(starter);const [active,setActive]=useState("About");const [saved,setSaved]=useState(false);const [notice,setNotice]=useState("");const [showPreview,setShowPreview]=useState(false);const [auth,setAuth]=useState(false);
 useEffect(()=>{const s=localStorage.getItem("folio-resume");if(s){try{setResume(JSON.parse(s))}catch{}}},[]);
 const save=()=>{localStorage.setItem("folio-resume",JSON.stringify(resume));setSaved(true);setNotice("All changes saved");setTimeout(()=>{setSaved(false);setNotice("")},2200)};
 const update=(key:keyof Resume,value:any)=>setResume(r=>({...r,[key]:value}));
 const updItem=(group:"experience"|"education",i:number,key:string,value:string)=>setResume(r=>({...r,[group]:r[group].map((item,n)=>n===i?{...item,[key]:value}:item)}));
 const addItem=(group:"experience"|"education")=>setResume(r=>({...r,[group]:[...r[group],group==="experience"?{role:"New role",company:"Company",dates:"2024 — Present",description:"Add your impact and accomplishments here."}:{degree:"Degree or certification",school:"School or institution",dates:"2020 — 2024"}]}));
 const removeItem=(group:"experience"|"education",i:number)=>setResume(r=>({...r,[group]:r[group].filter((_,n)=>n!==i)}));
 const sections=["About","Experience","Education","Skills","Style"];
 const completion=useMemo(()=>Math.min(100,Math.round([resume.name,resume.role,resume.email,resume.summary,resume.experience.length>0?"y":"",resume.education.length>0?"y":"",resume.skills].filter(Boolean).length/7*100)),[resume]);
 const exportPDF=()=>{window.print()};
 const reset=()=>{setResume(starter);localStorage.removeItem("folio-resume");setNotice("Starter resume restored")};
 const authSubmit=async(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=new FormData(e.currentTarget);if(form.get("mode")==="register"&&!String(form.get("name")||"").trim()){setNotice("Please enter your name to create an account.");return}const endpoint=process.env.NEXT_PUBLIC_API_URL||"http://localhost:5000";try{const res=await fetch(`${endpoint}/api/auth/${form.get("mode")}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:form.get("name"),email:form.get("email"),password:form.get("password")})});const data=await res.json();setNotice(res.ok?`${data.message} — signed in as ${data.user?.name||form.get("email")}`:(data.message||"Could not connect"));}catch{setNotice("Could not reach the backend. Check NEXT_PUBLIC_API_URL and try again.")}setAuth(false);setTimeout(()=>setNotice(""),4500)};
 return <main className={styles.app} style={{"--accent":resume.accent} as React.CSSProperties}>
  <header className={styles.topbar}><a className={styles.brand} href="#"><span className={styles.brandMark}><FileText size={18}/></span><span>folio<span className={styles.brandDot}>.</span></span></a><div className={styles.docTitle}><span className={styles.docName}>{resume.name || "Untitled resume"}</span><span className={styles.saveState}><i className={saved?styles.savedDot:styles.dot}/>{saved?"Saved":"Draft"}</span></div><div className={styles.topActions}><button className={styles.ghostBtn} onClick={reset}><RotateCcw size={15}/>Reset</button><button className={styles.ghostBtn} onClick={()=>setAuth(true)}><UserRound size={15}/>Sign in</button><button className={styles.primaryBtn} onClick={exportPDF}><Download size={16}/>Download PDF</button><button className={`${styles.primaryBtn} ${styles.mobilePreview}`} onClick={()=>setShowPreview(!showPreview)}><Eye size={16}/>Preview</button></div></header>
  <div className={styles.workspace}><aside className={styles.sidebar}><div className={styles.sideIntro}><span className={styles.eyebrow}>YOUR WORKSPACE</span><h1>Resume builder</h1><p>Make your next move a confident one.</p></div><div className={styles.progressCard}><div className={styles.progressLabel}><span>Resume strength</span><strong>{completion}%</strong></div><div className={styles.progressTrack}><span style={{width:`${completion}%`}}/></div><small>{completion>85?"Looking great — ready to share!":"A little more detail makes a big difference."}</small></div><div className={styles.sideLabel}>BUILD YOUR STORY</div><nav className={styles.sectionNav}>{sections.map((s,i)=><button key={s} className={`${styles.navItem} ${active===s?styles.navActive:""}`} onClick={()=>{setActive(s);setShowPreview(false)}}><span className={styles.navNum}>{String(i+1).padStart(2,"0")}</span><span>{s}</span>{active===s&&<span className={styles.navArrow}>→</span>}</button>)}</nav><div className={styles.sidebarBottom}><div className={styles.tipCard}><span className={styles.tipIcon}><Sparkles size={15}/></span><strong>A little tip</strong><p>Lead with outcomes. Numbers help your impact stand out.</p></div><button className={styles.helpLink} onClick={()=>setNotice("Tip: Write a short, specific summary. Highlight outcomes in each role.")}>Need a little inspiration? <ArrowRight size={13}/></button></div></aside>
   <section className={`${styles.editor} ${showPreview?styles.hideOnMobile:""}`}><div className={styles.editorHead}><div><span className={styles.eyebrow}>STEP {String(sections.indexOf(active)+1).padStart(2,"0")} OF 05</span><h2>{active==="About"?"The basics":active==="Style"?"Make it yours":active}</h2><p>{active==="About"?"A clear introduction helps the right people find you.":active==="Experience"?"Show the work, the thinking, and the difference you made.":active==="Education"?"Add education, training, or the learning that shaped you.":active==="Skills"?"A few relevant skills make your strengths easy to scan.":"Choose a look that feels like you."}</p></div><button className={styles.saveBtn} onClick={save}><Check size={15}/>Save</button></div>
   <div className={styles.formScroll}>
    {active==="About"&&<div className={styles.form}><div className={styles.field}><label>FULL NAME</label><input value={resume.name} onChange={e=>update("name",e.target.value)} placeholder="e.g. Alex Morgan"/></div><div className={styles.field}><label>PROFESSIONAL TITLE</label><input value={resume.role} onChange={e=>update("role",e.target.value)} placeholder="e.g. Product Designer"/></div><div className={styles.twoCol}><div className={styles.field}><label>EMAIL ADDRESS</label><input value={resume.email} onChange={e=>update("email",e.target.value)} placeholder="you@email.com"/></div><div className={styles.field}><label>PHONE</label><input value={resume.phone} onChange={e=>update("phone",e.target.value)} placeholder="+1 555 000 0000"/></div></div><div className={styles.twoCol}><div className={styles.field}><label>LOCATION</label><input value={resume.location} onChange={e=>update("location",e.target.value)} placeholder="City, Country"/></div><div className={styles.field}><label>WEBSITE / LINKEDIN</label><div className={styles.inputIcon}><Link2 size={15}/><input value={resume.website} onChange={e=>update("website",e.target.value)} placeholder="yourwebsite.com"/></div></div></div><div className={styles.field}><div className={styles.labelRow}><label>PROFILE SUMMARY</label><button className={styles.aiBtn} onClick={()=>setNotice("Try: ‘I’m a [role] who helps [audience] achieve [impact].’ Add a specific result to make it yours.")}><WandSparkles size={13}/> Writing tip</button></div><textarea rows={5} value={resume.summary} onChange={e=>update("summary",e.target.value)} placeholder="A few sentences about what you do, what you care about, and the value you bring."/><span className={styles.helper}>Keep it human, specific, and under 4 sentences.</span></div></div>}
    {active==="Experience"&&<div className={styles.form}>{resume.experience.map((item,i)=><div className={styles.entry} key={i}><div className={styles.entryHead}><span className={styles.entryIndex}>EXPERIENCE {String(i+1).padStart(2,"0")}</span><button className={styles.iconBtn} aria-label="Remove experience" onClick={()=>removeItem("experience",i)}><Trash2 size={15}/></button></div><div className={styles.field}><label>JOB TITLE</label><input value={item.role} onChange={e=>updItem("experience",i,"role",e.target.value)}/></div><div className={styles.twoCol}><div className={styles.field}><label>COMPANY</label><input value={item.company} onChange={e=>updItem("experience",i,"company",e.target.value)}/></div><div className={styles.field}><label>DATES</label><input value={item.dates} onChange={e=>updItem("experience",i,"dates",e.target.value)}/></div></div><div className={styles.field}><label>WHAT DID YOU ACHIEVE?</label><textarea rows={4} value={item.description} onChange={e=>updItem("experience",i,"description",e.target.value)} placeholder="Use a new line for each accomplishment."/><span className={styles.helper}>Action + impact is a powerful combination.</span></div></div>)}<button className={styles.addBtn} onClick={()=>addItem("experience")}><Plus size={16}/>Add experience</button></div>}
    {active==="Education"&&<div className={styles.form}>{resume.education.map((item,i)=><div className={styles.entry} key={i}><div className={styles.entryHead}><span className={styles.entryIndex}>EDUCATION {String(i+1).padStart(2,"0")}</span><button className={styles.iconBtn} aria-label="Remove education" onClick={()=>removeItem("education",i)}><Trash2 size={15}/></button></div><div className={styles.field}><label>DEGREE / PROGRAM</label><input value={item.degree} onChange={e=>updItem("education",i,"degree",e.target.value)}/></div><div className={styles.twoCol}><div className={styles.field}><label>SCHOOL / INSTITUTION</label><input value={item.school} onChange={e=>updItem("education",i,"school",e.target.value)}/></div><div className={styles.field}><label>DATES</label><input value={item.dates} onChange={e=>updItem("education",i,"dates",e.target.value)}/></div></div></div>)}<button className={styles.addBtn} onClick={()=>addItem("education")}><Plus size={16}/>Add education</button></div>}
    {active==="Skills"&&<div className={styles.form}><div className={styles.skillsIntro}><div className={styles.skillsBadge}><Sparkles size={20}/></div><div><strong>Your strengths, at a glance</strong><p>Mix tools, craft, and the way you work best.</p></div></div><div className={styles.field}><label>SKILLS & EXPERTISE</label><textarea rows={7} value={resume.skills} onChange={e=>update("skills",e.target.value)} placeholder="Product strategy · Figma · User research"/><span className={styles.helper}>Separate each skill with a middle dot (·) or comma.</span></div><div className={styles.suggested}><label>QUICK ADD</label><div className={styles.chips}>{["Leadership","Communication","Analytics","Accessibility","Agile","Storytelling"].map(s=><button key={s} className={styles.chip} onClick={()=>update("skills",resume.skills?`${resume.skills} · ${s}`:s)}><Plus size={12}/>{s}</button>)}</div></div></div>}
    {active==="Style"&&<div className={styles.form}><div className={styles.field}><label>CHOOSE A TEMPLATE</label><div className={styles.templateGrid}>{["Editorial","Modern","Minimal"].map((t,i)=><button key={t} onClick={()=>update("template",t)} className={`${styles.templateCard} ${resume.template===t?styles.templateSelected:""}`}><div className={`${styles.templateMini} ${styles[`mini${i}`]}`}><i/><i/><i/><i/><i/></div><span>{t}</span>{resume.template===t&&<Check size={14}/>}</button>)}</div></div><div className={styles.field}><label>ACCENT COLOR</label><div className={styles.swatches}>{colors.map(c=><button key={c} aria-label={`Choose color ${c}`} onClick={()=>update("accent",c)} className={`${styles.swatch} ${resume.accent===c?styles.swatchActive:""}`} style={{background:c}}>{resume.accent===c&&<Check size={15}/>}</button>)}</div></div><div className={styles.styleNote}><LayoutTemplate size={18}/><p>Your style updates instantly in the live preview. Keep contrast high and your content easy to scan.</p></div></div>}
   </div><div className={styles.editorFooter}><span>Made for your next chapter <span className={styles.brandDot}>✳</span></span><div className={styles.footerBtns}><button className={styles.footerBtn} onClick={()=>setActive(sections[Math.max(0,sections.indexOf(active)-1)])}><ArrowLeft size={15}/>Back</button><button className={styles.nextBtn} onClick={()=>{const i=sections.indexOf(active);if(i<sections.length-1)setActive(sections[i+1]);else setShowPreview(true)}}>{active==="Style"?"Preview resume":"Continue"}<ArrowRight size={15}/></button></div></div></section>
   <section className={`${styles.previewPane} ${showPreview?styles.showOnMobile:""}`}><div className={styles.previewToolbar}><div><span className={styles.previewStatus}><i/>LIVE PREVIEW</span><span className={styles.previewSub}>Updates as you edit</span></div><div className={styles.zoomActions}><button title="Preview resume"><Eye size={15}/></button><button title="Download as PDF" onClick={exportPDF}><Download size={15}/></button></div></div><div className={styles.paperWrap}><article className={`${styles.paper} ${styles[resume.template.toLowerCase()]}`}><header className={styles.paperHeader}><div className={styles.paperAccent}/><div className={styles.paperName}>{resume.name||"Your Name"}</div><div className={styles.paperRole}>{resume.role||"Professional Title"}</div><div className={styles.paperContact}>{[resume.email,resume.phone,resume.location,resume.website].filter(Boolean).join("  ·  ")}</div></header>{resume.summary&&<section className={styles.paperSection}><h3>PROFILE</h3><p>{resume.summary}</p></section>}{resume.experience.length>0&&<section className={styles.paperSection}><h3>EXPERIENCE</h3>{resume.experience.map((x,i)=><div className={styles.paperEntry} key={i}><div className={styles.paperEntryTitle}>{x.role}<span>{x.dates}</span></div><div className={styles.paperCompany}>{x.company}</div><ul>{x.description.split("\n").filter(Boolean).map((line,j)=><li key={j}>{line}</li>)}</ul></div>)}</section>}{resume.education.length>0&&<section className={styles.paperSection}><h3>EDUCATION</h3>{resume.education.map((x,i)=><div className={styles.paperEntry} key={i}><div className={styles.paperEntryTitle}>{x.degree}<span>{x.dates}</span></div><div className={styles.paperCompany}>{x.school}</div></div>)}</section>}{resume.skills&&<section className={styles.paperSection}><h3>CORE SKILLS</h3><p>{resume.skills.split(/[·,]/).map(s=>s.trim()).filter(Boolean).join("  ·  ")}</p></section>}<div className={styles.paperFoot}>{resume.name||"Your name"} <span>·</span> {resume.role||"Your profession"}</div></article></div><div className={styles.previewBottom}><span><span className={styles.kbd}>A4</span> Standard page size</span><button onClick={exportPDF}><Download size={14}/>Export PDF</button></div></section>
  </div>{notice&&<div className={styles.toast}><Check size={15}/>{notice}</div>}{auth&&<div className={styles.modalOverlay} onClick={()=>setAuth(false)}><form className={styles.authModal} onClick={e=>e.stopPropagation()} onSubmit={authSubmit}><button type="button" className={styles.modalClose} onClick={()=>setAuth(false)}>×</button><div className={styles.brandMark}><FileText size={18}/></div><h2>Welcome to folio.</h2><p>Connect to your account to get started.</p><label>MODE<select name="mode"><option value="login">Sign in</option><option value="register">Create account</option></select></label><label>NAME <small>(for registration)</small><input name="name" placeholder="Your name"/></label><label>EMAIL<input name="email" type="email" required placeholder="you@email.com"/></label><label>PASSWORD<input name="password" type="password" required placeholder="At least 8 characters"/></label><button className={styles.primaryBtn} type="submit">Continue <ArrowRight size={15}/></button><small className={styles.backendHint}>Uses the existing Express API. Configure NEXT_PUBLIC_API_URL to connect.</small></form></div>}
 </main>
}
